routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin-show-login')->middleware(['locale']);
Route::post('admin/login', 'Admin\Auth\LoginController@login')->name('admin.login');
Route::get('admin/set-locale/{locale}', 'Admin\Auth\LoginController@setLocale')->name('admin.locale');

Route::get('admin/get-client', 'Admin\OAuthClientController@index')->middleware(['cus_auth_not_redirect']); // get client ID & client secret

// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.reset.password');

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Admin',
    'as'        => 'admin.',
    'middleware' => ['acl.role', 'locale']
], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('admin-profile');
    Route::get('/logout', 'Auth\LoginController@adminLogout')->name('logout');


    /**
     * User
     */
    Route::post('/users/more', 'UserController@more')->name('users.more');
    Route::get('/users/{user}/trash', 'UserController@trash')->name('users.trash');
    Route::get('/users/{user}/restore', 'UserController@restore')->name('users.restore');
    Route::post('/users/email/existed', 'UserController@checkEmailExist')->name('users.checkEmailExist');
    Route::post('/users/trash-multi', 'UserController@trashMultiple')->name('users.trash_multi');
    Route::post('/users/delete-multi', 'UserController@deleteMultiple')->name('users.delete_multi');
    Route::post('/users/restore-multi', 'UserController@restoreMultiple')->name('users.restore_multi');
    Route::get('/users/update-profile', 'UserController@getUpdateProfile')->name('users.updateProfile');
    Route::put('/users/update-profile', 'UserController@postUpdateProfile')->name('users.updateProfile');
    Route::resource('/users', 'UserController');

    /**
     * Author
     */
    Route::get('/authors/search/{q?}', 'AuthorController@search')->name('authors.search');
    Route::resource('/authors', 'AuthorController');
    Route::post('/authors/more', 'AuthorController@more')->name('authors.more');
    Route::get('/authors/{author}/trash', 'AuthorController@trash')->name('authors.trash');
    Route::get('/authors/{author}/restore', 'AuthorController@restore')->name('authors.restore');
    Route::post('/authors/bulk-trash-multi', 'AuthorController@trashMulti')->name('authors.bulk_trash_multi');
    Route::post('/authors/restore-multi', 'AuthorController@restoreMulti')->name('authors.restore_multi');
    Route::post('/authors/delete-multi', 'AuthorController@deleteMulti')->name('authors.delete_multi');

    /**
     * Salutations
     */
    Route::resource('/salutations', 'SalutationController');
    Route::post('/salutations/more', 'SalutationController@more')->name('salutations.more');

    /**
     * Media
     */
    Route::get('/media', 'ComponentController@media')->name('media.index');

    /**
     * News
     */
    Route::post('/news/ajax-related-news-pagination', 'NewsController@moreRelatedNews')->name('news.moreRelatedNews');
    Route::get('/news/search/{q?}', 'NewsController@search')->name('news.search');
    Route::resource('/news', 'NewsController');
    Route::post('/news/more', 'NewsController@more')->name('news.more');
    Route::get('/news/{news}/trash', 'NewsController@trash')->name('news.trash');
    Route::get('/news/{news}/restore', 'NewsController@restore')->name('news.restore');
    Route::post('/news/apply', 'NewsController@apply')->name('news.apply');
    Route::post('/news/bulk-trash-multi', 'NewsController@trashMulti')->name('news.bulk_trash_multi');
    Route::post('/news/restore-multi', 'NewsController@restoreMulti')->name('news.restore_multi');
    Route::post('/news/delete-multi', 'NewsController@deleteMulti')->name('news.delete_multi');

    /**
     * Categories
     */
    Route::resource('/categories', 'CategoryController');
    Route::post('/categories/more', 'CategoryController@more')->name('categories.more');

    /**
     * Tags
     */
    Route::resource('/tags', 'TagController');
    Route::post('/tags/more', 'TagController@more')->name('tags.more');

    /**
     * General settings
     */
    Route::get('/settings', 'GeneralSettingController@edit')->name('settings.edit');
    Route::put('/settings', 'GeneralSettingController@update')->name('settings.update');

    /**
     * App
     */
    Route::get('/app/push-notification', 'PushNotificationController@getPushNotification')->name('app.push-notification');
    Route::post('/app/push-notification', 'PushNotificationController@postPushNotification')->name('app.send.push-notification');
    Route::get('/app/settings', 'AppSettingController@edit')->name('app.settings.edit');
    Route::put('/app/settings', 'AppSettingController@update')->name('app.settings.update');
    Route::get('/app/layout/settings/{key}', 'AppLayoutController@getLayoutSettings')->name('app.layout.settings');
    Route::post('/app/layout/settings/{key}', 'AppLayoutController@saveLayoutSettings')->name('app.layout.settings.save');
    Route::any('/app/layout/setting/{key}', 'AppLayoutController@settingContent')->name('app.layout.setting');
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Services\User\Admin\UpdateUserService;
use App\Services\User\Admin\SingleUserService;
use App\Services\User\Admin\DeleteUserService;
use App\Services\User\Admin\ListingUserService;
use App\Http\Requests\Admin\User\StoreUserRequest;
use App\Services\User\Admin\StoreUserService;
use Illuminate\Http\Request;
use Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbs = [
            [ 'text' => __('Users') ],
        ];

        $table = [
            'title' => 'Users Overview',
            'id' => 'users-datatable',
            'ajax' => [
                'src' => 'admin.users.more', // route name
            ],
            'order_default' => [
                'column' => 'created_at',
                'order' => 'desc'
            ],
            'actions_ajax' => [
                'bulk_trash_multi' => [
                    'route' => 'admin.users.trash_multi', // route name
                    'method' => 'post'
                ],
                'delete_multi' => [
                    'route' => 'admin.users.delete_multi', // route name
                    'method' => 'post',
                ],
                'restore_multi'   => [
                    'route' => 'admin.users.restore_multi', // route name
                    'method' => 'post',
                ]
            ],
            'checkbox_column' => true,
            'columns' => [
                'id' => ['text' => '#'],
                'name_with_link' => [
                    'text' => 'Name',
                    'filter' => [
                        'type' => 'input',
                    ],
                    'orderable' => true,
                ],
                'email' => [
                    'text' => 'Email',
                    'filter' => [
                        'type' => 'input',
                    ],
                    'orderable' => true,
                ],
                'phone' => [
                    'text' => 'Phone',
                    'filter' => [
                        'type' => 'input',
                    ],
                    'orderable' => true,
                ],
                'status' => [
                    'text' => 'Status',
                    'html' => '<i class="fa fa-check font-green-jungle tooltips" data-placement="top" data-original-title="Publish"></i>',
                    'filter' => [
                        'type' => 'select',
                        'data' => [
                            config('elidev.list_default_status.pending') => config('elidev.list_default_status.pending'),
                            config('elidev.list_default_status.publish') => config('elidev.list_default_status.publish'),
                        ],
                    ],
                    'orderable' => true,
                ],
                'created_at' => [ 'text' => 'Created at' ],
            ],
            'actions' => [
                'width'  => '100',
                'show' => [
                    'route' => 'admin.users.show', // route name
                    'role' => 'users.read',
                ],
                'add'    => [
                    'name'  => 'Add new',
                    'route' => 'admin.users.create', // route name
                    'icon'  => 'fa fa-fw fa-user-plus',
                    'role' => 'users.create',
                ],
                'edit'   => [
                    'route' => 'admin.users.edit', // route name
                    'role' => 'users.edit',
                ],
                'trash' => [
                    'route' => 'admin.users.trash', // route name
                    'icon' => 'fa fa-trash',
                    'color' => 'red-intense',
                    'role' => 'users.trash',
                ],
                'restore'   => [
                    'route' => 'admin.users.restore', // route name
                    'color' => 'green-jungle',
                    'role' => 'users.trash',
                ],
                'delete' => [
                    'route' => 'admin.users.destroy', // route name
                    'icon' => 'fa fa-times',
                    'color' => 'red-intense',
                    'role' => 'users.destroy',
                ],
            ],
        ];

        return view('admin.users.index', [
            'table' => $table,
            'breadcrumbs' => $breadcrumbs,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $breadcrumbs = [
            [
                'url' => route('admin.users.index'),
                'text' => __('Users')
            ],
            [
                'text' => __('Create'),
            ],
        ];

        return view('admin.users.create', [
            'breadcrumbs' => $breadcrumbs,
            'list_default_status' => config('elidev.list_default_status'),
            'overrideClass' => true,
            'dataAjaxUrl' => route('admin.users.checkEmailExist')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Admin\User\StoreUserRequest $request
     * @param  \App\Services\User\Admin\StoreUserService $service
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request, StoreUserService $service)
    {
        $user = $service->execute($request);

        if ( $user ) {
            return redirect(route('admin.users.show', [ 'user' => $user->id ]))
                ->with('success', __('Create user successfully'))
                ->withInput();
        }

        return back()->with('error', __('Create failed. Please try again'))->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @param $request
     * @param $service
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id, SingleUserService $service)
    {
        $request->merge(['id' => $id]);
        $user = $service->execute($request);

        if ( !$user ) {
            abort(404);
        }

        $breadcrumbs = [
            [
                'url' => route('admin.users.index'),
                'text' => __('Users')
            ],
            [
                'text' => sprintf('%s', $user->name),
            ],
        ];

        return view('admin.users.show', [
            'user'      => $user,
            'breadcrumbs' => $breadcrumbs,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int $id
     * @param $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id, SingleUserService $service)
    {
        $request->merge(['id' => $id]);
        $user = $service->execute($request);

        if ( !$user ) {
            abort(404);
        }

        $breadcrumbs = [
            [
                'url' => route('admin.users.index'),
                'text' => __('Users')
            ],
            [
                'url' => route('admin.users.show', ['user' => $user->id]),
                'text' => sprintf('%s', $user->name),
            ],
            [
                'text' => __('Edit'),
            ],
        ];

        return view('admin.users.edit', [
            'user'      => $user,
            'list_default_status' => config('elidev.list_default_status'),
            'breadcrumbs' => $breadcrumbs,
            'overrideClass' => true,
            'dataAjaxUrl' => route('admin.users.checkEmailExist'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param   $request
     * @param  int $id
     * @param $service
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUserRequest $request, $id, UpdateUserService $service)
    {
        $request->merge(['id' => $id]);
        $result = $service->execute($request);

        $key     = $result ? 'success' : 'error';
        $message = $result ? __('Updated successfully') : __('Update failed. Please try again');

        return back()->with($key, $message);
    }

    /**
     * Trash the specified resource from storage.
     *
     * @param  int                                       $id
     * @param \App\Services\User\Admin\DeleteUserService $service
     *
     * @return \Illuminate\Http\Response
     * @ticket #12893 - HFBACKEND-12 - Author - Trash/Destroy action
     */
    public function trash($id, DeleteUserService $service)
    {
        if ( $service->softDelete($id) ) {
            return redirect(route('admin.users.index'))->with('success', __('Trashed user successfully'));
        }

        Log::error(sprintf('Failed to trash the user (ID = %s).', $id));

        return back()->with('error', __('Failed to trash the user. Please try again.'));
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int                                       $id
     * @param \App\Services\User\Admin\DeleteUserService $service
     *
     * @return \Illuminate\Http\Response
     * @ticket #12893 - HFBACKEND-12 - Author - Trash/Destroy action
     */
    public function restore($id, DeleteUserService $service)
    {
        if ( $service->restore($id) ) {
            return back()->with('success', __('Restored user successfully'));
        }

        Log::error(sprintf('Failed to restore the user (ID = %s).', $id));

        return back()->with('error', __('Failed to restore the user. Please try again.'));
    }

    /**
     * Remove the specified resource from storage.
     *

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('title', __('Profile'))

@section('body_class')
    page-logged page-logged-personal js-page-logged
@endsection

@section('sub_header')
    @component('partial.components.sub_headers.green')
        @slot('row')
            <div class="blk-welcome">
                <p>{{ __('My Personal Settings') }}</p>
            </div>
        @endslot
    @endcomponent
@endsection

@php
    $classCss = 'hidden';
    $classMessageCss = '';
    if($user->avatar){
        $classCss = '';
        $classMessageCss = 'hidden';
    }

@endphp


@section('content')
    <div class="blk-personal--setting">
        <div class="container container-custom">
            <div class="blk-all-form frm-personal--setting">
                <form action="{{ route('users.update', ['id' => $user->id]) }}" data-url="{{ route('users.update', ['id' => $user->id]) }}" enctype="multipart/form-data" method="POST" id="edit-user-profile-form" >
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group field-group">
                                <input class="form-control ipt--field" type="text" name="name" value="{{$user->name}}" required>
                                <label class="label--field" for="name">* {{__('NAME')}}</label>
                                <label class="error" style="display: none" for="name"></label>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group field-group">
                                <input class="form-control ipt--field"
                                       type="text"
                                       name="email"
                                       value="{{$user->email}}"
                                       data-ajax-url="{{route('emailExisted')}}"
                                       required
                                >
                                <label class="label--field" for="email">* {{__('EMAIL')}}</label>
                                <label class="error" style="display: none" for="email"></label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group field-group">
                                <input class="form-control ipt--field" type="password" name="password" id="password" required>
                                <label class="label--field" for="password">{{__('New password')}}</label>
                                <label class="error" style="display: none" for="password"></label>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group field-group">
                                <input class="form-control ipt--field" type="password" name="password_confirmation" required>
                                <label class="label--field" for="password_confirmation">{{__('Repeat new password')}}</label>
                                <label class="error" style="display: none" for="password_confirmation"></label>
                            </div>
                        </div>
                    </div>
                    <div class="blk-upload--profile">


                        <div class="blk-upload--profile">
                            <a class="btn-upload-img js-upload--profile {{ !empty($user) && $user->avatar ? 'have-img' : '' }}"
                               type="button"
                            >
                                <span class="ttl--upload {{ $classMessageCss }}"> {{__('Upload')}} <br>{{__('Profile Photo')}}</span>
                                <span class="type--upload {{ $classMessageCss }}">@include('partial.image_extension_logo', compact('imageRules'))</span>
                                <input
                                        class="ipt-upl js-ipt--url"
                                        type="file"
                                        name="avatar"
                                        onchange="NameField.previewUpload(this)"
                                >
                                <span class="preview--img  {{$classCss}}" style="background-image: url('{{ $user->avatar }}');"></span>
                                <span class="remove-img--preview {{$classCss}} " onclick="NameField.removePreview(this)">
                                   <img src="{{ asset('img/ico-close-white.png') }}" alt="">
                                </span>
                            </a>

                            <br>
                            <p class="message">
                                <label class="error" style="display: none" for="avatar"></label>
                            </p>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group select-group"><label class="label-select--field" for="select-country">{{__('COUNTRY')}}</label>
                                <select class="form-control js-render-select--option" name="country" id="select-country" allow-search>
                                    <option value="-1" > {{__('Select')}}  </option>
                                    @foreach($countries as $country)
                                        @php
                                            $code = strtolower($country['code']);
                                            $name = strtolower($country['name']);
                                        @endphp
                                        <option value="{{ $code }}" @if(strtolower($user->country) == $code) selected @endif>{{ $country['name'] }}</option>
                                    @endforeach
                                </select>
                                <div class="wrapper-spinner wrapper-spinner-green load-data--dropdown"><i class="icon icon-circle-o-notch"></i></div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group field-group">
                                <input class="form-control ipt--field" value="{{$user->city}}" type="text" name="city"  required>
                                <label class="label--field" for="city">{{__('City')}}</label>
                                <label class="error" style="display: none" for="city"></label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group field-group @if($user->country == -1 || empty($user->country)) un-active @endif">
                                <input class="form-control ipt--field" type="text" id="phone"  data-country="" name="phone" value="{{$user->phone}}" @if($user->country == -1 || empty($user->country)) readonly="readonly" @endif>
                                <label class="label--field phone-label" for="phone">{{__('PHONE')}}</label>
                                <label class="error" style="display: none" for="phone"></label>
                            </div>
                        </div>

                    </div>
                    <div class="form-action-row">
                        <div class="message"></div>

                    <button class="btn btn-green btn-save" type="submit">{{__('Save')}}</button>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/thankyou.blade.php
@extends('layouts.app')

@section('title', __('Thank you for signing up'))

@section('body_class')
    page-sign-up page-sign-up--thanks
@endsection


@section('content')
    <div class="signup-blk thky-blk">
        <div class="p-container">
            <h2 class="p-ttl">{{__('Thank you!')}}</h2>
            <div class="p-desc">
                {{ $thankYou }}
            </div>
        </div>
    </div>
@endsection

resources/views/user/unsubscribe.blade.php
@extends('layouts.app')

@section('title', __('Unsubscribe receiving notification email'))

@section('body_class')
    page-deed
@endsection

@section('content')
    <div class="signup-blk thky-blk">
        <div class="p-container">
            <div class="p-desc">{{ $message }}.</div>
        </div>
    </div>
@endsection