routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin-show-login')->middleware(['locale']);
Route::post('admin/login', 'Admin\Auth\LoginController@login')->name('admin.login');
Route::get('admin/set-locale/{locale}', 'Admin\Auth\LoginController@setLocale')->name('admin.locale');

Route::get('admin/get-client', 'Admin\OAuthClientController@index')->middleware(['cus_auth_not_redirect']); // get client ID & client secret

// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.reset.password');

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Admin',
    'as'        => 'admin.',
    'middleware' => ['acl.role', 'locale']
], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('admin-profile');
    Route::get('/logout', 'Auth\LoginController@adminLogout')->name('logout');


    /**
     * User
     */
    Route::post('/users/more', 'UserController@more')->name('users.more');
    Route::get('/users/{user}/trash', 'UserController@trash')->name('users.trash');
    Route::get('/users/{user}/restore', 'UserController@restore')->name('users.restore');
    Route::post('/users/email/existed', 'UserController@checkEmailExist')->name('users.checkEmailExist');
    Route::post('/users/trash-multi', 'UserController@trashMultiple')->name('users.trash_multi');
    Route::post('/users/delete-multi', 'UserController@deleteMultiple')->name('users.delete_multi');
    Route::post('/users/restore-multi', 'UserController@restoreMultiple')->name('users.restore_multi');
    Route::get('/users/update-profile', 'UserController@getUpdateProfile')->name('users.updateProfile');
    Route::put('/users/update-profile', 'UserController@postUpdateProfile')->name('users.updateProfile');
    Route::resource('/users', 'UserController');

    /**
     * Author
     */
    Route::get('/authors/search/{q?}', 'AuthorController@search')->name('authors.search');
    Route::resource('/authors', 'AuthorController');
    Route::post('/authors/more', 'AuthorController@more')->name('authors.more');
    Route::get('/authors/{author}/trash', 'AuthorController@trash')->name('authors.trash');
    Route::get('/authors/{author}/restore', 'AuthorController@restore')->name('authors.restore');
    Route::post('/authors/bulk-trash-multi', 'AuthorController@trashMulti')->name('authors.bulk_trash_multi');
    Route::post('/authors/restore-multi', 'AuthorController@restoreMulti')->name('authors.restore_multi');
    Route::post('/authors/delete-multi', 'AuthorController@deleteMulti')->name('authors.delete_multi');

    /**
     * Salutations
     */
    Route::resource('/salutations', 'SalutationController');
    Route::post('/salutations/more', 'SalutationController@more')->name('salutations.more');

    /**
     * Media
     */
    Route::get('/media', 'ComponentController@media')->name('media.index');

    /**
     * News
     */
    Route::post('/news/ajax-related-news-pagination', 'NewsController@moreRelatedNews')->name('news.moreRelatedNews');
    Route::get('/news/search/{q?}', 'NewsController@search')->name('news.search');
    Route::resource('/news', 'NewsController');
    Route::post('/news/more', 'NewsController@more')->name('news.more');
    Route::get('/news/{news}/trash', 'NewsController@trash')->name('news.trash');
    Route::get('/news/{news}/restore', 'NewsController@restore')->name('news.restore');
    Route::post('/news/apply', 'NewsController@apply')->name('news.apply');
    Route::post('/news/bulk-trash-multi', 'NewsController@trashMulti')->name('news.bulk_trash_multi');
    Route::post('/news/restore-multi', 'NewsController@restoreMulti')->name('news.restore_multi');
    Route::post('/news/delete-multi', 'NewsController@deleteMulti')->name('news.delete_multi');

    /**
     * Categories
     */
    Route::resource('/categories', 'CategoryController');
    Route::post('/categories/more', 'CategoryController@more')->name('categories.more');

    /**
     * Tags
     */
    Route::resource('/tags', 'TagController');
    Route::post('/tags/more', 'TagController@more')->name('tags.more');

    /**
     * General settings
     */
    Route::get('/settings', 'GeneralSettingController@edit')->name('settings.edit');
    Route::put('/settings', 'GeneralSettingController@update')->name('settings.update');

    /**
     * App
     */
    Route::get('/app/push-notification', 'PushNotificationController@getPushNotification')->name('app.push-notification');
    Route::post('/app/push-notification', 'PushNotificationController@postPushNotification')->name('app.send.push-notification');
    Route::get('/app/settings', 'AppSettingController@edit')->name('app.settings.edit');
    Route::put('/app/settings', 'AppSettingController@update')->name('app.settings.update');
    Route::get('/app/layout/settings/{key}', 'AppLayoutController@getLayoutSettings')->name('app.layout.settings');
    Route::post('/app/layout/settings/{key}', 'AppLayoutController@saveLayoutSettings')->name('app.layout.settings.save');
    Route::any('/app/layout/setting/{key}', 'AppLayoutController@settingContent')->name('app.layout.setting');
});

app/Http/Controllers/APIs/V1/SettingController.php
<?php

namespace App\Http\Controllers\APIs\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Contracts\CategoryRepositoryInterface;
use App\Repositories\Contracts\TagsRepositoryInterface;
use Settings;

class SettingController extends Controller
{
    /**
     * Get current font in Admin Panel
     *
     * @return mixed
     * @ticket #13182 - HFBACKEND-39 - App / possibility to select name of font family. This list is hardcoded
     */
    public function getCurrentFont()
    {
        return response()->success(Settings::get(config('fomo.app_settings.font'), __('The font is not set')));
    }

    /**
     * Get current layout dashboard in Admin Panel
     *
     * @return mixed
     */
    public function getCurrentLayoutDashboard()
    {
        $data = Settings::get(config('fomo.app_settings.app_layout_dashboard'));
        return response()->success($data, __('The layout dashboard is not set'));
    }

    /**
     * Get current layout news dashboard in Admin Panel
     *
     * @return \Illuminate\Http\Response
     * @ticket #13291 - HFBACKEND-80 App / Layout News Dashboard - UI concept
     */
    public function getCurrentLayoutNewsDashboard()
    {
        $data = Settings::get(config('fomo.app_settings.app_layout_news'));
        return response()->success($data, __('The layout news is not set'));
    }
}

resources/views/admin/setting/edit.blade.php
@extends('admin.layout.admin')

@php
    $title            = __('Edit Setting');
    $supportLanguages = config('fomo.support_languages');
    $dateTimeKeyEn    = config('fomo.settings.date_time_en');
    $dateTimeKeyDe    = config('fomo.settings.date_time_de');
    $languageKey      = config('fomo.settings.language');
    $file_types       = config('fomo.settings.news_files_types');
@endphp

@section('title', $title)

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="profile-content">
                <div class="row">
                    <form role="form" action="{{ route('admin.settings.update') }}" method="POST" class="form-horizontal form-validation submit-frm">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="col-md-12">
                            <div class="portlet light bordered no-padding-bottom">
                                <div class="portlet-title">
                                    <div class="caption font-green">{{ empty($title) ? __('Form General Settings') : $title }}</div>
                                    <div class="actions">
                                        @include('admin.components.full-screen')
                                    </div>
                                </div>

                                <div class="portlet-body form">
                                    <div class="tabbable-custom">
                                        <ul class="nav nav-tabs">
                                            <li class="active">
                                                <a href="#tab_1_1_1" data-toggle="tab"> {{ __('General') }} </a>
                                            </li>
                                            <li>
                                                <a href="#tab_1_1_2" data-toggle="tab"> {{ __('Date & Time') }} </a>
                                            </li>
                                            <li>
                                                <a href="#tab_1_1_3" data-toggle="tab"> {{ __('News') }} </a>
                                            </li>
                                        </ul>
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="tab_1_1_1">
                                                <div class="form-group Elidev\ACL\Controllers {{ $errors->has($languageKey) ? 'has-error' : '' }}">
                                                    <label class="col-md-2 control-label" for="{{ $languageKey }}">{{ __('Language') }}</label>

                                                    <div class="col-md-6">
                                                        <select name="{{ $languageKey }}" id="{{ $languageKey }}" class="form-control">
                                                            @foreach($supportLanguages as $name => $code)
                                                                <option value="{{ $code }}" @if (isset($settings[$languageKey]) && $settings[$languageKey] == $code) selected @endif >{{ $name }}</option>
                                                            @endforeach
                                                        </select>
                                                        <div class="form-control-focus"></div>
                                                        <span class="help-block">{{ $errors->first($languageKey) }}</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="tab-pane" id="tab_1_1_2">
                                                <div class="form-group Elidev\ACL\Controllers {{ $errors->has($dateTimeKeyEn) ? 'has-error' : '' }}">
                                                    <label class="col-md-2 control-label" for="{{ $dateTimeKeyEn }}">{{ __('English') }}</label>

                                                    <div class="col-md-6">
                                                        <input type="text"
                                                               class="form-control"
                                                               name="{{ $dateTimeKeyEn }}"
                                                               id="{{ $dateTimeKeyEn }}"
                                                               placeholder="{{ __('Y/m/d H:i') }}"
                                                               value="{{ old($dateTimeKeyEn, isset($settings[$dateTimeKeyEn]) ? $settings[$dateTimeKeyEn] : '') }}">
                                                        <div class="form-control-focus"></div>
                                                        <span class="help-block">{{ $errors->first($dateTimeKeyEn) }}</span>
                                                    </div>
                                                </div>

                                                <div class="form-group Elidev\ACL\Controllers {{ $errors->has($dateTimeKeyDe) ? 'has-error' : '' }}">
                                                    <label class="col-md-2 control-label" for="{{ $dateTimeKeyDe }}">{{ __('Germany') }}</label>

                                                    <div class="col-md-6">
                                                        <input type="text"
                                                               class="form-control"
                                                               name="{{ $dateTimeKeyDe }}"
                                                               id="{{ $dateTimeKeyDe }}"
                                                               placeholder="{{ __('d.m.Y H:i') }}"
                                                               value="{{ old($dateTimeKeyDe, isset($settings[$dateTimeKeyDe]) ? $settings[$dateTimeKeyDe] : '') }}">
                                                        <div class="form-control-focus"></div>
                                                        <span class="help-block">{{ $errors->first($dateTimeKeyDe) }}</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="tab-pane" id="tab_1_1_3">
                                                <div class="form-group Elidev\ACL\Controllers {{ $errors->has($file_types) ? 'has-error' : '' }}">
                                                    <label class="col-md-2 control-label" for="{{ $file_types }}">{{ __('Files Types') }}</label>

                                                    <div class="col-md-6">
                                                        <input type="text"
                                                               class="form-control"
                                                               name="{{ $file_types }}"
                                                               id="{{ $file_types }}"
                                                               placeholder="{{ __('For example: png,jpeg,jpg,gif') }}"
                                                               value="{{ old($file_types, isset($settings[$file_types]) ? $settings[$file_types] : '') }}">
                                                        <div class="form-control-focus"></div>
                                                        <span class="help-block">{{ $errors->first($file_types) }}</span>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection