routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin-show-login')->middleware(['locale']);
Route::post('admin/login', 'Admin\Auth\LoginController@login')->name('admin.login');
Route::get('admin/set-locale/{locale}', 'Admin\Auth\LoginController@setLocale')->name('admin.locale');

Route::get('admin/get-client', 'Admin\OAuthClientController@index')->middleware(['cus_auth_not_redirect']); // get client ID & client secret

// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.reset.password');

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Admin',
    'as'        => 'admin.',
    'middleware' => ['acl.role', 'locale']
], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('admin-profile');
    Route::get('/logout', 'Auth\LoginController@adminLogout')->name('logout');


    /**
     * User
     */
    Route::post('/users/more', 'UserController@more')->name('users.more');
    Route::get('/users/{user}/trash', 'UserController@trash')->name('users.trash');
    Route::get('/users/{user}/restore', 'UserController@restore')->name('users.restore');
    Route::post('/users/email/existed', 'UserController@checkEmailExist')->name('users.checkEmailExist');
    Route::post('/users/trash-multi', 'UserController@trashMultiple')->name('users.trash_multi');
    Route::post('/users/delete-multi', 'UserController@deleteMultiple')->name('users.delete_multi');
    Route::post('/users/restore-multi', 'UserController@restoreMultiple')->name('users.restore_multi');
    Route::get('/users/update-profile', 'UserController@getUpdateProfile')->name('users.updateProfile');
    Route::put('/users/update-profile', 'UserController@postUpdateProfile')->name('users.updateProfile');
    Route::resource('/users', 'UserController');

    /**
     * Author
     */
    Route::get('/authors/search/{q?}', 'AuthorController@search')->name('authors.search');
    Route::resource('/authors', 'AuthorController');
    Route::post('/authors/more', 'AuthorController@more')->name('authors.more');
    Route::get('/authors/{author}/trash', 'AuthorController@trash')->name('authors.trash');
    Route::get('/authors/{author}/restore', 'AuthorController@restore')->name('authors.restore');
    Route::post('/authors/bulk-trash-multi', 'AuthorController@trashMulti')->name('authors.bulk_trash_multi');
    Route::post('/authors/restore-multi', 'AuthorController@restoreMulti')->name('authors.restore_multi');
    Route::post('/authors/delete-multi', 'AuthorController@deleteMulti')->name('authors.delete_multi');

    /**
     * Salutations
     */
    Route::resource('/salutations', 'SalutationController');
    Route::post('/salutations/more', 'SalutationController@more')->name('salutations.more');

    /**
     * Media
     */
    Route::get('/media', 'ComponentController@media')->name('media.index');

    /**
     * News
     */
    Route::post('/news/ajax-related-news-pagination', 'NewsController@moreRelatedNews')->name('news.moreRelatedNews');
    Route::get('/news/search/{q?}', 'NewsController@search')->name('news.search');
    Route::resource('/news', 'NewsController');
    Route::post('/news/more', 'NewsController@more')->name('news.more');
    Route::get('/news/{news}/trash', 'NewsController@trash')->name('news.trash');
    Route::get('/news/{news}/restore', 'NewsController@restore')->name('news.restore');
    Route::post('/news/apply', 'NewsController@apply')->name('news.apply');
    Route::post('/news/bulk-trash-multi', 'NewsController@trashMulti')->name('news.bulk_trash_multi');
    Route::post('/news/restore-multi', 'NewsController@restoreMulti')->name('news.restore_multi');
    Route::post('/news/delete-multi', 'NewsController@deleteMulti')->name('news.delete_multi');

    /**
     * Categories
     */
    Route::resource('/categories', 'CategoryController');
    Route::post('/categories/more', 'CategoryController@more')->name('categories.more');

    /**
     * Tags
     */
    Route::resource('/tags', 'TagController');
    Route::post('/tags/more', 'TagController@more')->name('tags.more');

    /**
     * General settings
     */
    Route::get('/settings', 'GeneralSettingController@edit')->name('settings.edit');
    Route::put('/settings', 'GeneralSettingController@update')->name('settings.update');

    /**
     * App
     */
    Route::get('/app/push-notification', 'PushNotificationController@getPushNotification')->name('app.push-notification');
    Route::post('/app/push-notification', 'PushNotificationController@postPushNotification')->name('app.send.push-notification');
    Route::get('/app/settings', 'AppSettingController@edit')->name('app.settings.edit');
    Route::put('/app/settings', 'AppSettingController@update')->name('app.settings.update');
    Route::get('/app/layout/settings/{key}', 'AppLayoutController@getLayoutSettings')->name('app.layout.settings');
    Route::post('/app/layout/settings/{key}', 'AppLayoutController@saveLayoutSettings')->name('app.layout.settings.save');
    Route::any('/app/layout/setting/{key}', 'AppLayoutController@settingContent')->name('app.layout.setting');
});

resources/views/admin/partials/breadcrumb.blade.php
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{ route('admin.dashboard') }}">{{ __('Dashboard') }}</a>

            @if ( isset($breadcrumbs) )
                <i class="fa fa-angle-right"></i>
            @endif
        </li>

        @if ( isset($breadcrumbs) && count($breadcrumbs) > 0 )
            @foreach($breadcrumbs as $key => $breadcrumb)
                <li>
                    @if ( array_get($breadcrumb, 'url', '') == '' )
                        <span>{{ array_get($breadcrumb, 'text', '') }}</span>
                    @else
                        <a href="{{ array_get($breadcrumb, 'url', 'javascript:;') }}">{{ array_get($breadcrumb, 'text', '') }}</a>
                    @endif
                </li>
                @if ( !$loop->last )
                    <li><i class="fa fa-angle-right"></i></li>
                @endif
            @endforeach
        @endif
    </ul>

    <?php
    try {
        $params = request()->route()->parameters;
        $routeName = request()->route()->getName();
        list(, $mod, $action) = explode('.', $routeName);
        $key = key($params);
        $id = reset($params);
    }
    catch(Exception $e) {}
    ?>
    @if (isset($action))

        <?php
        try {

            $isACLRoute = strpos(\Request::route()->getName(), 'acl.');
            $prefix = $isACLRoute !== false ? 'acl':'admin';
            $createRoute = route(sprintf("%s.$mod.create", $prefix));
        }
        catch(Exception $e){}
        ?>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <div class="actions">

                    {{-- Save App dashboard layout settings >> --}}
                    @if ( $routeName == 'admin.app.layout.settings' )
                        @php $routeKey = Request::is('admin/app/layout/settings/dashboard') ? 'dashboard' : 'news'; @endphp
                        <a href="javascript:;"
                           id="fomo-save-app-dashboard-layout-btn"
                           class="btn btn-icon-only btn-default tooltips"
                           data-placement="bottom"
                           data-original-title="{{ __("Save") }}"
                           data-ajax-url="{{ route('admin.app.layout.settings.save', ['key' => $routeKey]) }}">
                            <i class="fa fa-save"></i>
                        </a>
                    @endif
                    {{-- Save App dashboard layout settings << --}}

                    {{-- Save App layout setting contact --}}
                    @if ( in_array($routeName, ['admin.settings.edit', 'admin.app.layout.setting', 'admin.app.settings.edit']) )
                        <a id="fomo-save-btn" data-placement="bottom" data-original-title="{{ __("Save") }}" href="" class="btn btn-icon-only btn-default tooltips ">
                            <i class="fa fa-save"></i>
                        </a>
                    @endif
                    {{-- Save App layout setting contact --}}


                    @if ($action == 'show')
                        <?php
                        try {
                            $editRoute = !empty($key) && !empty($id) ? route('admin.'.$mod.'.edit', [$key  => $id]) : '';
                        }
                        catch(Exception $e) {}
                        ?>
                        @if (!empty($editRoute))
                            <a data-placement="bottom" data-original-title="{{ __("Edit") }}" data-acl-role="{{ $mod }}.edit" href="{{ $editRoute }}" class="btn btn-icon-only btn-default tooltips">
                                <i class="fa fa-edit"></i>
                            </a>
                        @endif
                    @endif

                    @if (($action == 'create' || $action == 'edit' || $action == 'edit-assign') && $routeName != 'admin.settings.edit' )
                        <?php $action = $action != 'create' ? 'edit':$action ?>
                        <a id="fomo-save-btn" data-placement="bottom"
                           data-error-msg="{{ __("There are some errors in the form, please review") }}"
                           data-original-title="{{ __("Save") }}" data-acl-role="{{ $mod }}.{{$action}}" href="" class="btn btn-icon-only btn-default tooltips {{ isset($overrideClass) && $overrideClass ? 'fomo-override-save-action' : '' }}" data-ajax-url="{{ isset($dataAjaxUrl) ? $dataAjaxUrl : '' }}" user-id="{{ isset($user) ? $user->id : '' }}">
                            <i class="fa fa-save"></i>
                        </a>
                    @endif

                    @if (!empty($id) && !empty($key) && $action != 'show' && !in_array($mod, ['tags', 'categories', 'salutations']))
                        <?php
                        try {
                            $viewRoute = route('admin.'.$mod.'.show', [$key  => $id]);
                        }
                        catch(Exception $e) {}
                        ?>
                        @if (!empty($viewRoute))
                            <a id="fomo-view-btn" data-placement="bottom" data-original-title="{{ __("View") }}" data-acl-role="{{ $mod }}.read" href="{{ isset($viewRoute) ? $viewRoute : '' }}" class="btn btn-icon-only btn-default tooltips">
                                <i class="fa fa-search"></i>
                            </a>
                        @endif
                    @endif

                    @if ($action != 'create' && !empty($createRoute))
                        <a id="fomo-create-btn" data-placement="bottom" data-original-title="{{ __("New") }}" data-acl-role="{{ $mod }}.create" href="{{ $createRoute }}" class="btn btn-icon-only btn-default tooltips green">
                            <i class="fa fa-plus"></i>
                        </a>
                    @endif

                    @if (($action == 'edit' || $action == 'show') && !empty($key) && !empty($id))
                        <?php
                        try {
                            $trashRoute = route('admin.'.$mod.'.trash', [$key  => $id]);
                        }
                        catch(Exception $e) {}
                        ?>
                        @if (! empty($trashRoute))
                            <a data-placement="bottom" data-original-title="{{ __("Move to trash") }}" data-acl-role="{{ $mod }}.trash" href="{{ isset($trashRoute) ? $trashRoute : '' }}" class="btn btn-icon-only btn-default tooltips red-intense">
                                <i class="fa fa-trash"></i>
                            </a>
                        @endif
                    @endif

                    @if (in_array($action, ['edit', 'show']) && in_array($mod, ['categories', 'salutations', 'tags']))
                        <?php
                        try {
                            $destroyRoute = route('admin.'.$mod.'.destroy', [$key  => $id]);
                        }
                        catch(Exception $e) {}
                        ?>
                        @if (!empty($destroyRoute))
                            <a id="fomo-single-delete-btn" data-placement="bottom" data-original-title="{{ __("Delete forever") }}" data-acl-role="{{ $mod }}.destroy" href="" class="btn btn-icon-only btn-default tooltips red-intense">
                                <i class="fa fa-remove"></i>
                            </a>
                            <div class="modal fade" id="fomo-single-confirm-delete-modal" tabindex="-1" role="basic" aria-hidden="true">
                                <div class="modal-dialog">
                                    <form method="POST" action="{{ $destroyRoute }}">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                <h4 class="modal-title">{{ __("Delete permanently") }}</h4>
                                            </div>
                                            <div class="modal-body">{{ __('Do you want to delete permanently?') }}</div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn dark btn-outline btn-close" data-dismiss="modal">{{ __('Close') }}</button>
                                                <button type="submit" class="btn red btn-action">{{ __('Delete permanently') }}</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        @endif
                    @endif

                </div>
            </div>
        </div>
    @endif

</div>

resources/views/admin/partials/page_footer.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        &copy; {{ date('Y') }} {{ __('Fomosapiens') }}
    </div>
</div>
<!-- END FOOTER -->

resources/views/admin/partials/page_header.blade.php
@php
    $user = Auth::user();
@endphp

<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="{{ route('admin.dashboard') }}">
                <img src="{{ asset('fomo_logo.png') }}" alt="logo" class="logo-default"/>
            </a>
            <div class="menu-toggler sidebar-toggler">
                <span></span>
            </div>
        </div>
        <!-- END LOGO -->

        <!-- BEGIN TOP NAVIGATION MENU -->
        <?php $locale = session('locale', config('app.locale')) ?>
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <li class="dropdown dropdown-language">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        @if ($locale == 'en')
                            <img alt="" src="/admin-assets/global/img/flags/us.png"/>
                            <span class="langname">{{ __("EN") }} </span><i class="fa fa-angle-down"></i>
                        @else
                            <img alt="" src="/admin-assets/global/img/flags/de.png"/>
                            <span class="langname">{{ __("DE") }} </span><i class="fa fa-angle-down"></i>
                        @endif
                    </a>

                    <ul class="dropdown-menu dropdown-menu-default">
                        <li class="{{ $locale == 'de' ? 'active' : '' }}">
                            <a href="{{ route('admin.locale', ['locale' => 'de']) }}">
                                <img alt="" src="/admin-assets/global/img/flags/de.png"> {{ __("DE") }} </a>
                        </li>

                        <li class="{{ $locale == 'en' ? 'active' : '' }}">
                            <a href="{{ route('admin.locale', ['locale' => 'en']) }}">
                                <img alt="" src="/admin-assets/global/img/flags/us.png"> {{ __("EN") }} </a>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->

                <!-- BEGIN USER LOGIN DROPDOWN -->
                @php $img_avatar = !empty($user->image_src) ?  get_image_url($user->image_src, 'thumb') : null @endphp
                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle" src="{{ $img_avatar ? $img_avatar : asset('default_user.png') }}"/>
                        <span class="username">{{ $user ? $user->name : __('Administrator') }} </span><i class="fa fa-angle-down"></i>
                    </a>

                    <ul class="dropdown-menu">
                        <li>
                            <a href="#" id="admin-bar-edit-profile" data-url="{{ route("admin.users.updateProfile") }}">
                                <i class="icon-user"></i> {{ __('My Profile') }}
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->

                <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                <li class="dropdown dropdown-quick-sidebar-toggler">
                    <a href="{{ route('admin.logout') }}" class="dropdown-toggle">
                        <i class="icon-logout"></i>
                    </a>
                </li>
                <!-- END QUICK SIDEBAR TOGGLER -->
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<div class="clearfix"></div>
<!-- END HEADER -->

<div class="modal fade" id="fomo-modal-update-profile" role="basic" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <form action="" data-url="{{ route("admin.users.updateProfile") }}">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">{{ __('Update profile') }}</h4>
                </div>

                <div class="modal-body">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline btn-close pull-left" data-dismiss="modal">{{ __('Close') }}</button>
                    <button type="submit" class="btn btn-default green pull-right">{{ __('Update') }}</button>
                </div>
                <div class="spinner-loading font-green text-center" style="display: none"><i class="fa fa-spinner fa-spin fa-3x"></i></div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>